### ISSUE TITLE
Named Entity Recognizer

### ISSUE THREAD

**Issue by jserigos** [Bilingual-Annotation-Task-Force/python-tagger#3]
From my understanding in the Evaluation and Annotator modules, the NER evaluates at the word level so multi-grams will not be properly recognized, (ex. "Los Angeles", "El Paso", "the United Nations") . We had discussed creating two layers of annotation to resolve this. 
1. NE 
2. Eng, Spn, Punct, Num 

So our output could look like (using the Beginning-Inside-Outside system):
- Los, NE-B, Spn
- Angeles, NE-I, Spn
- es, NE-O, Spn
- grande, NE-O, Spn

My first thought was evaluating the corpus as a whole through the Eng and Spn NER and then going word by word through the corpus for the language level. I did notice that in Killer Cronicas, while Los Angeles is not recognized as NE, the compound Buenos Aires is so I'm not sure how that happened...

**Comment by jserigos** [comment]
I thought of another solution that wouldn't involve passing through the corpus twice so it will be more efficient. 
for word, run the NER on the [index-2:index+2] list. this will give the NER the context it needs. I just check this from their [online tester](http://nlp.stanford.edu:8080/ner/process) "Los Angeles" --> Location while "Los" --> 0 and "Angeles" -->0
I'll create a separate branch to play with this idea.

**Comment by kelseyball** [comment]
I wonder if we can run the whole corpus through as a pre-processing step?
If I remember from the demo/docs online, the examples passed in a paragraph.
